import { test, expect } from '@playwright/test';
const password = 'Test-password-for-PIT-2026';
test('dos aplicaciones: registro, servicio, canje, aislamiento y sesión persistente', async ({ page, browser }, testInfo) => {
  const email = `cliente-${testInfo.project.name}@example.test`, errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#admin');
  await page.getByRole('button', { name: 'Registrarse', exact: true }).click();
  await page.getByLabel('Nombre', { exact: true }).fill('Cliente MVP');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(page.locator('.points-value')).toHaveText('0pts');
  await expect(page.locator('#service-form')).toHaveCount(0);
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain(password);
  expect(await page.evaluate(() => document.cookie)).not.toContain('session');
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const admin = await context.newPage(); admin.on('pageerror', error => errors.push(error.message));
    await admin.goto('http://127.0.0.1:3102');
    await admin.getByLabel('Correo electrónico').fill(email);
    await admin.getByLabel('Contraseña', { exact: true }).fill(password);
    await admin.getByRole('button', { name: 'Entrar a administración' }).click();
    await expect(admin.getByRole('alert')).toContainText('incorrectos para este portal');
    await expect(admin.locator('#service-form')).toHaveCount(0);
    await admin.getByLabel('Correo electrónico').fill('admin@example.test');
    await admin.getByLabel('Contraseña', { exact: true }).fill(password);
    await admin.getByRole('button', { name: 'Entrar a administración' }).click();
    await admin.getByLabel('Buscar cliente').fill(email);
    await admin.getByRole('button', { name: 'Buscar', exact: true }).click();
    await expect(admin.locator('.customer-item')).toHaveCount(1);
    await admin.locator('.customer-item').filter({ hasText: email }).getByRole('button', { name: 'Abrir cliente' }).click();
    await admin.getByLabel('Servicio', { exact: true }).selectOption('Lavado de moto');
    await admin.getByLabel('Importe pagado (USD)').fill('5');
    await admin.getByRole('button', { name: 'Registrar y sumar puntos' }).click();
    await expect(admin.locator('#admin-status')).toContainText('Servicio registrado');
    await page.reload(); await expect(page.locator('.points-value')).toHaveText('5.000pts');
    await admin.getByLabel('Servicio', { exact: true }).selectOption('Detailing integral');
    await admin.getByLabel('Importe pagado (USD)').fill('250');
    await admin.getByRole('button', { name: 'Registrar y sumar puntos' }).click();
    await expect(admin.locator('.admin-member')).toContainText('255.000 puntos');
    await page.reload(); await expect(page.locator('.points-value')).toHaveText('255.000pts');
    await page.getByRole('button', { name: 'Beneficios', exact: true }).click();
    await page.locator('[data-offer="oil"]').click();
    await page.getByRole('button', { name: 'Generar código de canje' }).click();
    const code = await page.locator('.redemption-code').textContent();
    await expect(page.getByRole('button', { name: 'Probar validación en el negocio' })).toHaveCount(0);
    await admin.getByLabel('Código de canje').fill(code);
    await admin.getByLabel('He comprobado').check();
    await admin.getByRole('button', { name: 'Validar canje', exact: true }).click();
    await expect(admin.locator('#admin-status')).toContainText('Canje validado');
    await page.goto('/#home'); await page.reload();
    await expect(page.locator('.points-value')).toHaveText('155.000pts');
    await page.goto('/#admin'); await expect(page.locator('#service-form')).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    expect(await admin.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
    await admin.screenshot({ path: `test-results/admin-${testInfo.project.name}.png`, fullPage: true });
    await admin.getByRole('button', { name: 'QR del club', exact: true }).click();
    await admin.getByLabel('URL pública del club').fill('https://moriarty369.github.io/pit-detail-club/');
    await admin.getByRole('button', { name: 'Generar QR', exact: true }).click();
    await expect(admin.locator('#entry-canvas')).toBeVisible();
    await page.goto('/#profile');
    await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Iniciar sesión', exact: true })).toBeVisible();
    await page.reload(); await expect(page.locator('.points-value')).toHaveCount(0);
    await page.getByLabel('Correo electrónico').fill(email);
    await page.getByLabel('Contraseña', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Continuar', exact: true }).click();
    await expect(page.locator('.points-value')).toHaveText('155.000pts');
    expect(errors).toEqual([]);
  } finally { await context.close().catch(() => {}); }
});
